In [2]:
import re
import json
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [3]:
resp = requests.get("https://sciencedata.dk/public/082a018b1f2fd125ef4907f01ab2e2cf/") # 2025
#resp = requests.get("https://sciencedata.dk/public/ede416946cfd3b35dcf1e61ac68da5de") # 2024
soup = BeautifulSoup(resp.content, "html.parser")
address = []
for item in soup.find_all("a"):
    href = item.get('href')
    if href and '.json' in href:
        address.append(href)
address[:10]

['/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0253P_site_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0253P_site_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_gis_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_gis_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_gis_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_gis_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_http_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_http_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_http_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_http_2.json']

In [4]:
len(address)

1464

In [5]:
address = list(set(address))
len(address)

732

In [6]:
address[:10]

['/public/082a018b1f2fd125ef4907f01ab2e2cf/F24B0288P_nlp_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24B0242P_python_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/%20F24B0254P_python_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24B0296P_gis_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24B0307P_pdf_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24B0072K_site_3.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/Tvrz%20-%20test_python_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0035P_pdf_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24B0259P_gis_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24B0297P_nlp_1.json']

In [11]:
[a for a in address if "F24N0039P" in a]

['/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_gis_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_nlp_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_http_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_pdf_2.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_http_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_site_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_nlp_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_pdf_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_gis_1.json',
 '/public/082a018b1f2fd125ef4907f01ab2e2cf/F24N0039P_site_2.json']

In [7]:
# dávala:
# F1HUMBP2 -> F23B0267P (Preislerová)

In [8]:
data = []
for item in address:
    resp = requests.get('https://sciencedata.dk' + str(item))
    data.append(json.loads(resp.text))

KeyboardInterrupt:

In [102]:
data_df = pd.DataFrame(data)

In [103]:
data_df.to_json("../data/data_df.json")

In [104]:
#data_df = pd.read_json("../data/data_df.json")

In [105]:
data_df.head(5)

           user     ntb                      time       arg1  arg2  n
0   F2476878678  python  Mon Feb 24 12:56:28 2025       1920  None  1
1  F24B0_blabla  python  Mon Feb 24 14:47:12 2025       1920  None  1
2     F24B0271P     abm  Mon Apr 28 11:56:13 2025          2  None  2
3     F24B0335P    http  Wed Apr 23 13:44:40 2025      http2  None  4
4     F24B0277P     gis  Mon Mar 10 13:28:25 2025  kontrola2  None  2

In [107]:
def clean_user(user):
    try:
        return re.search(r"F\d+\w\d+[PK]?", user.replace("O", "0"), re.IGNORECASE).group()
    except: 
        print(user)
data_df["osCislo"] = data_df["user"].apply(clean_user)
data_df.head(5)

test
test
58955475
Tvrz - test
5848755
test
testkase
K24B0013B
test
dfkci2k
test
test
test
test
test
test
test
test
test
74185296
import os

,user,ntb,time,arg1,arg2,n,osCislo
0,F2476878678,python,Mon Feb 24 12:56:28 2025,1920,None,1,F2476878678
1,F24B0_blabla,python,Mon Feb 24 14:47:12 2025,1920,None,1,F24B0
2,F24B0271P,abm,Mon Apr 28 11:56:13 2025,2,None,2,F24B0271P
3,F24B0335P,http,Wed Apr 23 13:44:40 2025,http2,None,4,F24B0335P
4,F24B0277P,gis,Mon Mar 10 13:28:25 2025,kontrola2,None,2,F24B0277P

In [108]:
table = data_df.groupby(["osCislo", "ntb"]).size().unstack(fill_value=0)
table = table.clip(upper=2)
table.reset_index(inplace=True)
table

ntb       osCislo  abm  api  gis  http  nlp  pdf  python  regex  site
0       F06688787    0    0    0     0    0    0       0      0     1
1       F06799978    0    0    0     0    0    0       0      0     1
2       F20B0045P    0    0    0     0    0    0       1      0     0
3      F224B0248P    0    0    0     0    1    0       0      0     0
4        F240032K    0    0    0     0    0    0       0      0     1
5     F2476878678    0    0    0     0    0    0       1      0     0
6    F24797878087    0    0    0     0    0    0       1      0     0
7           F24B0    0    0    0     0    0    0       1      0     0
8       F24B0006K    0    0    1     0    0    0       0      0     2
9       F24B0009K    0    0    1     0    0    0       0      0     2
10      F24B0013K    0    0    1     0    0    0       0      0     2
11      F24B0018K    0    0    2     0    0    0       0      0     2
12      F24B0020K    0    0    2     0    0    0       0      0     2
13      F24B0028K    0    0    0     0    0    0       0      0     2
14      F24B0032K    0    0    2     0    0    0       0      0     2
15      F24B0033K    0    0    2     2    2    2       0      0     2
16      F24B0040P    1    0    0     0    2    2       0      0     0
17      F24B0045P    0    0    2     2    0    2       2      0     2
18      F24B0050P    0    0    2     2    2    2       0      0     2
19      F24B0072K    0    0    2     0    0    0       0      0     2
20      F24B0236P    0    0    2     2    2    2       2      2     2
21      F24B0242P    0    0    2     2    2    2       2      0     2
22      F24B0248P    2    0    2     2    1    2       1      2     2
23      F24B0250P    2    0    2     0    2    2       2      0     0
24      F24B0253P    0    2    2     2    0    0       2      2     2
25      F24B0254P    0    0    2     1    0    0       0      0     2
26      F24B0256P    0    0    2     2    2    2       1      0     2
27      F24B0257P    2    0    2     2    2    2       1      0     2
28      F24B0259P    2    0    2     2    2    2       0      2     2
29      F24B0264P    0    0    2     2    2    2       0      0     2
30      F24B0269P    0    0    0     0    0    0       0      0     2
31      F24B0271P    2    0    2     2    2    2       1      2     2
32      F24B0273P    2    0    2     2    2    2       0      0     2
33      F24B0274P    0    0    2     2    2    2       1      0     2
34      F24B0275P    2    0    2     2    2    2       1      0     2
35      F24B0277P    2    0    2     2    2    2       1      2     2
36      F24B0281P    2    0    2     2    2    2       1      2     2
37      F24B0284P    2    0    2     2    2    2       1      2     2
38      F24B0287P    0    0    2     2    2    2       0      0     2
39      F24B0288P    0    0    2     2    2    2       1      2     2
40      F24B0289P    0    0    2     2    2    2       1      0     2
41      F24B0292P    0    0    0     0    2    0       0      0     0
42      F24B0293P    2    0    2     2    2    2       1      2     2
43      F24B0296P    0    0    2     2    2    2       1      0     2
44      F24B0297P    0    0    2     2    2    0       0      0     2
45      F24B0306P    2    0    2     2    2    2       1      2     2
46      F24B0307P    2    0    2     2    2    2       2      2     2
47      F24B0309P    0    0    2     2    2    2       0      2     2
48      F24B0313P    2    0    2     0    2    2       2      0     0
49      F24B0320P    2    0    2     2    2    2       1      2     2
50      F24B0328P    0    0    2     2    2    2       1      0     2
51      F24B0335P    0    0    1     2    0    2       0      2     2
52      F24B0336P    0    0    2     2    2    2       1      0     2
53      F24B0337P    2    0    2     0    0    0       2      0     0
54      F24N0035P    0    0    2     2    2    2       2      0     2
55      F24N0039P    0    0    2     2    2    2       0      0     2
56       F2B0040P    1    0    0     0    0    0       0      0     0

In [109]:
students_df = pd.read_csv("../data/UDHB_students2025.csv", sep=";", encoding='cp1250')
students_df = students_df[students_df["stav"]=="S"]
students_df = students_df[["osCislo", "prijmeni","jmeno", "userName"]]
len(students_df)

73

In [110]:
merged_df = pd.merge(students_df, table, on="osCislo", how="left")
merged_df.fillna(0, inplace=True)
merged_df.head(5)

,osCislo,prijmeni,jmeno,userName,abm,api,gis,http,nlp,pdf,python,regex,site
0,F24B0211P,ANSLOVÁ,Tereza,anslovat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,F24B0254P,BÁRTOVÁ,Bára,bartova,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,2.0
2,F24B0256P,BENDOVÁ,Eliška,bendovae,0.0,0.0,2.0,2.0,2.0,2.0,1.0,0.0,2.0
3,F24B0257P,BLECHOVÁ,Barbora,blechovb,2.0,0.0,2.0,2.0,2.0,2.0,1.0,0.0,2.0
4,F24B0003K,BOROVSKÝ,Matěj,borym,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [111]:
merged_df = merged_df[["osCislo", "site", "gis", "http", "nlp", "pdf"]]
merged_df.head(5)

     osCislo  site  gis  http  nlp  pdf
0  F24B0211P   0.0  0.0   0.0  0.0  0.0
1  F24B0254P   2.0  2.0   1.0  0.0  0.0
2  F24B0256P   2.0  2.0   2.0  2.0  2.0
3  F24B0257P   2.0  2.0   2.0  2.0  2.0
4  F24B0003K   0.0  0.0   0.0  0.0  0.0

In [117]:
merged_df["sum"] = merged_df[["gis", "site", "http", "nlp", "pdf"]].sum(axis=1)

0      0.0
1      5.0
2     10.0
3     10.0
4      0.0
      ...
68     4.0
69     2.0
70     0.0
71     0.0
72    10.0
Length: 73, dtype: float64

In [114]:
import google_conf

cviceni_plneni = google_conf.setup(
    sheet_url="https://docs.google.com/spreadsheets/d/1DjmDNSVgiqxNjFzHWKZ1iBkK6NPlbL6gxohoH-kqUYg/edit?usp=sharing",
    service_account_path="../../../ServiceAccountsKey.json")

In [115]:
n = 0
sheet_created = False

while not sheet_created:
    try:
        # Attempt to create the worksheet with the appropriate name
        if n == 0:
            sheet_name = f"udhb_{date}"  # Default name
        else:
            sheet_name = f"udhb_{date}_{n}"  # Incremented name

        # Create the worksheet and upload the DataFrame
        google_conf.set_with_dataframe(cviceni_plneni.add_worksheet(sheet_name, rows=1, cols=1), merged_df.reset_index())
        sheet_created = True  # If successful, mark as created
    except Exception as e:
        # If it fails (likely because the name exists), increment the suffix and try again
        n += 1
        print(f"Worksheet with name '{sheet_name}' already exists. Trying another name...")

Worksheet with name 'udhb_2025-05-05' already exists. Trying another name...
Worksheet with name 'udhb_2025-05-05_1' already exists. Trying another name...

In [28]:
table["sum"] = table.sum(axis=1)

In [29]:
KDDHB_students_inverted = {value: key for key, value in KDDHB_students.items()}
KDDHB_students_inverted

{'BOHÁČKOVÁ': 'F22B0199P',
 'BOŠKOVÁ': 'F21B0005K',
 'BUCHEŇOVÁ': 'F22B0118P',
 'COUFALOVÁ': 'F22B0201P',
 'DĚDEČKOVÁ': 'F21B0164P',
 'GRUNDFESTOVÁ': 'F22B0211P',
 'HAVELOVÁ': 'F22B0030K',
 'HLAVÍNOVÁ': 'F21B0035K',
 'KELLNEROVÁ': 'F21B0022K',
 'KUBEŠOVÁ': 'F21B0028K',
 'KUBINCOVÁ': 'F22B0185P',
 'LAPKA': 'F22B0235P',
 'LE': 'F22B0198P',
 'NOVÁ': 'F21B0033K',
 'NOVÁK': 'F20B0539P',
 'PÁNKOVÁ': 'F22B0248P',
 'REMEŠOVÁ': 'F21B0040K',
 'ŠKAMPOVÁ': 'F22B0267P',
 'ŠLEFR': 'F22B0273P',
 'VOLOPICH': 'F21B0051K',
 'WISLOCKÁ': 'F21B0206P'}

In [30]:
table = table.reset_index()
table

ntb kddhb_students  api  gis  http  nlp  pdf  python  site  tei  sum
0        BOHÁČKOVÁ    2    2     2    2    0       2     2    2   14
1          BOŠKOVÁ    2    0     2    2    2       0     0    2   10
2        BUCHEŇOVÁ    2    2     2    2    0       2     2    2   14
3        COUFALOVÁ    2    2     2    2    0       2     0    2   12
4        DĚDEČKOVÁ    2    1     2    2    2       0     2    2   13
5     GRUNDFESTOVÁ    2    2     2    2    0       2     2    2   14
6         HAVELOVÁ    0    2     2    2    2       2     0    2   12
7        HLAVÍNOVÁ    2    1     2    2    2       1     0    2   12
8       KELLNEROVÁ    2    0     2    2    2       2     0    2   12
9         KUBEŠOVÁ    2    0     2    2    2       0     0    2   10
10       KUBINCOVÁ    0    2     2    2    2       2     2    0   12
11           LAPKA    0    2     2    2    2       2     2    2   14
12              LE    2    2     0    0    0       2     2    2   10
13            NOVÁ    2    1     2    1    2       0     0    2   10
14           NOVÁK    2    2     2    2    0       2     2    2   14
15         PÁNKOVÁ    0    2     2    2    0       2     2    2   12
16        REMEŠOVÁ    2    0     2    2    2       0     0    2   10
17        WISLOCKÁ    2    2     2    2    0       2     2    2   14
18        ŠKAMPOVÁ    2    2     2    2    2       2     2    2   16
19           ŠLEFR    2    2     2    2    2       0     0    2   12

In [31]:
table["osCislo"] = table["kddhb_students"].apply(lambda x: KDDHB_students_inverted[x])
table.drop(columns=["kddhb_students"], inplace=True)
table.set_index("osCislo", inplace=True)
table

ntb        api  gis  http  nlp  pdf  python  site  tei  sum
osCislo
F22B0199P    2    2     2    2    0       2     2    2   14
F21B0005K    2    0     2    2    2       0     0    2   10
F22B0118P    2    2     2    2    0       2     2    2   14
F22B0201P    2    2     2    2    0       2     0    2   12
F21B0164P    2    1     2    2    2       0     2    2   13
F22B0211P    2    2     2    2    0       2     2    2   14
F22B0030K    0    2     2    2    2       2     0    2   12
F21B0035K    2    1     2    2    2       1     0    2   12
F21B0022K    2    0     2    2    2       2     0    2   12
F21B0028K    2    0     2    2    2       0     0    2   10
F22B0185P    0    2     2    2    2       2     2    0   12
F22B0235P    0    2     2    2    2       2     2    2   14
F22B0198P    2    2     0    0    0       2     2    2   10
F21B0033K    2    1     2    1    2       0     0    2   10
F20B0539P    2    2     2    2    0       2     2    2   14
F22B0248P    0    2     2    2    0       2     2    2   12
F21B0040K    2    0     2    2    2       0     0    2   10
F21B0206P    2    2     2    2    0       2     2    2   14
F22B0267P    2    2     2    2    2       2     2    2   16
F22B0273P    2    2     2    2    2       0     0    2   12

In [32]:
table.to_csv("../data/kddhb_plneni.csv")

# UDHB

In [23]:
UDHB_students_inverted = {value: key for key, value in UDHB_students.items()}

In [24]:
table = data_df[data_df["udhb_students"].notnull()].groupby(["udhb_students", "ntb"]).size().unstack(fill_value=0)
table = table.clip(upper=2)

In [25]:
table = table.reset_index()
table

ntb udhb_students  abm  api  gis  http  nlp  pdf  python  regex  site
0         BENDOVÁ    0    0    2     2    2    2       1      0     2
1        BLECHOVÁ    2    0    2     2    2    2       1      0     2
2        BŘENDOVÁ    2    0    2     2    2    2       0      2     2
3       FRIEDLOVÁ    0    0    1     0    0    0       0      0     2
4        FUCHSOVÁ    0    0    2     0    0    0       0      0     2
5       HLAVNIČKA    0    0    0     0    0    0       0      0     2
6          HOROVÁ    2    0    2     2    2    2       1      2     2
7        JAROŠOVÁ    2    0    2     2    2    2       0      0     2
8         JEŽKOVÁ    0    0    2     2    2    2       1      0     2
9         JUNGOVÁ    1    0    0     0    2    2       0      0     0
10       KALINOVÁ    2    0    2     2    2    2       1      0     2
11         KOSOVÁ    2    0    2     2    2    2       1      2     2
12         KOUKAL    0    0    1     0    0    0       0      0     2
13        KOVALÍK    2    0    2     2    2    2       1      2     2
14        KRÁLOVÁ    0    0    2     2    2    2       2      2     2
15          KYLIŠ    0    0    2     2    2    2       0      0     2
16       LACINOVÁ    0    0    2     2    2    2       1      2     2
17      LIPTÁKOVÁ    0    0    2     2    0    0       1      0     2
18         MALINA    0    0    2     0    2    2       2      0     2
19     MATOUŠKOVÁ    2    0    2     2    2    0       1      2     2
20       MAŘÍKOVÁ    0    0    0     0    2    0       0      0     0
21         MEDOVÁ    0    0    2     0    0    0       0      0     2
22      MOLCAROVÁ    0    0    2     2    0    2       1      0     2
23      NEBŘENSKÁ    0    0    2     2    2    0       0      0     2
24   OKROUHLÍKOVÁ    0    0    2     0    0    0       0      0     2
25    PAVLIDISOVÁ    2    0    2     2    1    2       1      2     2
26      PERNETOVÁ    2    0    2     0    2    2       2      0     0
27       RAUSCHER    2    0    2     0    2    2       1      2     2
28      ROUBALOVÁ    0    2    2     2    0    0       2      2     2
29       RYBÁROVÁ    2    0    2     2    2    2       2      2     2
30     SEIDLEROVÁ    0    0    1     1    0    2       0      0     2
31       SKIRKOVÁ    0    0    2     2    2    2       0      2     2
32       SVAŠKOVÁ    2    0    2     0    2    2       2      0     0
33       TOMANOVÁ    0    0    2     2    2    2       1      0     0
34        VOKURKA    0    0    1     2    0    2       0      2     2
35         VRBOVÁ    0    0    2     2    2    1       1      0     2
36        ZAJÍČEK    0    0    2     2    2    2       0      0     2
37           ZÝKA    0    0    2     0    0    0       0      0     2
38       ČÁSTKOVÁ    0    0    1     0    0    0       0      0     2
39       ŠKOULOVÁ    0    0    2     2    0    2       2      0     2
40       ŠROUBOVÁ    2    0    2     2    2    2       1      2     2
41          ŠTICH    0    0    0     0    0    0       0      0     2
42        ŽENÍŠEK    2    0    2     2    2    2       1      2     2
43         ŽÁKOVÁ    2    0    2     0    0    0       2      0     0

In [26]:
table["osCislo"] = table["udhb_students"].apply(lambda x: UDHB_students_inverted[x])
udhb_students_series = table["udhb_students"]
#table.drop(columns=["udhb_students"], inplace=True)
table.set_index("osCislo", inplace=True)
table

ntb       udhb_students  abm  api  gis  http  nlp  pdf  python  regex  site
osCislo
F24B0256P       BENDOVÁ    0    0    2     2    2    2       1      0     2
F24B0257P      BLECHOVÁ    2    0    2     2    2    2       1      0     2
F24B0259P      BŘENDOVÁ    2    0    2     2    2    2       0      2     2
F24B0009K     FRIEDLOVÁ    0    0    1     0    0    0       0      0     2
F24B0264P      FUCHSOVÁ    0    0    2     0    0    0       0      0     2
F24B0269P     HLAVNIČKA    0    0    0     0    0    0       0      0     2
F24B0271P        HOROVÁ    2    0    2     2    2    2       1      2     2
F24B0273P      JAROŠOVÁ    2    0    2     2    2    2       0      0     2
F24B0274P       JEŽKOVÁ    0    0    2     2    2    2       1      0     2
F24B0040P       JUNGOVÁ    1    0    0     0    2    2       0      0     0
F24B0275P      KALINOVÁ    2    0    2     2    2    2       1      0     2
F24B0281P        KOSOVÁ    2    0    2     2    2    2       1      2     2
F24B0013K        KOUKAL    0    0    1     0    0    0       0      0     2
F24B0284P       KOVALÍK    2    0    2     2    2    2       1      2     2
F24B0236P       KRÁLOVÁ    0    0    2     2    2    2       2      2     2
F24B0287P         KYLIŠ    0    0    2     2    2    2       0      0     2
F24B0288P      LACINOVÁ    0    0    2     2    2    2       1      2     2
F24B0289P     LIPTÁKOVÁ    0    0    2     2    0    0       1      0     2
F24B0242P        MALINA    0    0    2     0    2    2       2      0     2
F24B0293P    MATOUŠKOVÁ    2    0    2     2    2    0       1      2     2
F24B0292P      MAŘÍKOVÁ    0    0    0     0    2    0       0      0     0
F24B0018K        MEDOVÁ    0    0    2     0    0    0       0      0     2
F24B0296P     MOLCAROVÁ    0    0    2     2    0    2       1      0     2
F24B0297P     NEBŘENSKÁ    0    0    2     2    2    0       0      0     2
F24B0020K  OKROUHLÍKOVÁ    0    0    2     0    0    0       0      0     2
F24B0248P   PAVLIDISOVÁ    2    0    2     2    1    2       1      2     2
F24B0250P     PERNETOVÁ    2    0    2     0    2    2       2      0     0
F24B0306P      RAUSCHER    2    0    2     0    2    2       1      2     2
F24B0253P     ROUBALOVÁ    0    2    2     2    0    0       2      2     2
F24B0307P      RYBÁROVÁ    2    0    2     2    2    2       2      2     2
F24B0050P    SEIDLEROVÁ    0    0    1     1    0    2       0      0     2
F24B0309P      SKIRKOVÁ    0    0    2     2    2    2       0      2     2
F24B0313P      SVAŠKOVÁ    2    0    2     0    2    2       2      0     0
F24B0328P      TOMANOVÁ    0    0    2     2    2    2       1      0     0
F24B0335P       VOKURKA    0    0    1     2    0    2       0      2     2
F24B0032K        VRBOVÁ    0    0    2     2    2    1       1      0     2
F24B0033K       ZAJÍČEK    0    0    2     2    2    2       0      0     2
F24B0072K          ZÝKA    0    0    2     0    0    0       0      0     2
F24B0006K      ČÁSTKOVÁ    0    0    1     0    0    0       0      0     2
F24B0045P      ŠKOULOVÁ    0    0    2     2    0    2       2      0     2
F24B0320P      ŠROUBOVÁ    2    0    2     2    2    2       1      2     2
F24B0028K         ŠTICH    0    0    0     0    0    0       0      0     2
F24B0277P       ŽENÍŠEK    2    0    2     2    2    2       1      2     2
F24B0337P        ŽÁKOVÁ    2    0    2     0    0    0       2      0     0

In [27]:
len(table)

44

In [28]:
udhb_povinne = ["udhb_students", "site", "gis", "http", "nlp", "pdf"]
table = table[udhb_povinne]
table

ntb       udhb_students  site  gis  http  nlp  pdf
osCislo
F24B0256P       BENDOVÁ     2    2     2    2    2
F24B0257P      BLECHOVÁ     2    2     2    2    2
F24B0259P      BŘENDOVÁ     2    2     2    2    2
F24B0009K     FRIEDLOVÁ     2    1     0    0    0
F24B0264P      FUCHSOVÁ     2    2     0    0    0
F24B0269P     HLAVNIČKA     2    0     0    0    0
F24B0271P        HOROVÁ     2    2     2    2    2
F24B0273P      JAROŠOVÁ     2    2     2    2    2
F24B0274P       JEŽKOVÁ     2    2     2    2    2
F24B0040P       JUNGOVÁ     0    0     0    2    2
F24B0275P      KALINOVÁ     2    2     2    2    2
F24B0281P        KOSOVÁ     2    2     2    2    2
F24B0013K        KOUKAL     2    1     0    0    0
F24B0284P       KOVALÍK     2    2     2    2    2
F24B0236P       KRÁLOVÁ     2    2     2    2    2
F24B0287P         KYLIŠ     2    2     2    2    2
F24B0288P      LACINOVÁ     2    2     2    2    2
F24B0289P     LIPTÁKOVÁ     2    2     2    0    0
F24B0242P        MALINA     2    2     0    2    2
F24B0293P    MATOUŠKOVÁ     2    2     2    2    0
F24B0292P      MAŘÍKOVÁ     0    0     0    2    0
F24B0018K        MEDOVÁ     2    2     0    0    0
F24B0296P     MOLCAROVÁ     2    2     2    0    2
F24B0297P     NEBŘENSKÁ     2    2     2    2    0
F24B0020K  OKROUHLÍKOVÁ     2    2     0    0    0
F24B0248P   PAVLIDISOVÁ     2    2     2    1    2
F24B0250P     PERNETOVÁ     0    2     0    2    2
F24B0306P      RAUSCHER     2    2     0    2    2
F24B0253P     ROUBALOVÁ     2    2     2    0    0
F24B0307P      RYBÁROVÁ     2    2     2    2    2
F24B0050P    SEIDLEROVÁ     2    1     1    0    2
F24B0309P      SKIRKOVÁ     2    2     2    2    2
F24B0313P      SVAŠKOVÁ     0    2     0    2    2
F24B0328P      TOMANOVÁ     0    2     2    2    2
F24B0335P       VOKURKA     2    1     2    0    2
F24B0032K        VRBOVÁ     2    2     2    2    1
F24B0033K       ZAJÍČEK     2    2     2    2    2
F24B0072K          ZÝKA     2    2     0    0    0
F24B0006K      ČÁSTKOVÁ     2    1     0    0    0
F24B0045P      ŠKOULOVÁ     2    2     2    0    2
F24B0320P      ŠROUBOVÁ     2    2     2    2    2
F24B0028K         ŠTICH     2    0     0    0    0
F24B0277P       ŽENÍŠEK     2    2     2    2    2
F24B0337P        ŽÁKOVÁ     0    2     0    0    0

In [29]:
table["sum"] = table[["site", "gis", "http", "nlp", "pdf"]].sum(axis=1)
(table["sum"] >= 8).sum()

/tmp/ipykernel_513892/2524964100.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table["sum"] = table[["site", "gis", "http", "nlp", "pdf"]].sum(axis=1)

np.int64(26)

In [30]:
table.head(5)

ntb       udhb_students  site  gis  http  nlp  pdf  sum
osCislo
F24B0256P       BENDOVÁ     2    2     2    2    2   10
F24B0257P      BLECHOVÁ     2    2     2    2    2   10
F24B0259P      BŘENDOVÁ     2    2     2    2    2   10
F24B0009K     FRIEDLOVÁ     2    1     0    0    0    3
F24B0264P      FUCHSOVÁ     2    2     0    0    0    4

In [41]:
table.to_csv("../data/udhb_povinne_prijmeni.csv")

In [31]:
table.drop(columns=["udhb_students"], inplace=True)

/tmp/ipykernel_513892/1350239464.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table.drop(columns=["udhb_students"], inplace=True)

In [32]:
table = table.sort_index()

In [34]:
import google_conf

In [35]:
cviceni_plneni = google_conf.setup(sheet_url="https://docs.google.com/spreadsheets/d/1DjmDNSVgiqxNjFzHWKZ1iBkK6NPlbL6gxohoH-kqUYg/edit?usp=sharing", service_account_path="../../../ServiceAccountsKey.json")

In [36]:
# get datetime for today in yyyy-mm-dd format:
date = pd.Timestamp.today().strftime("%Y-%m-%d")
date

'2025-05-05'

In [40]:
google_conf.set_with_dataframe(cviceni_plneni.add_worksheet("udhb_" + date, rows=1, cols=1), table.reset_index())

In [39]:
table.reset_index()

ntb    osCislo  site  gis  http  nlp  pdf  sum
0    F24B0006K     2    1     0    0    0    3
1    F24B0009K     2    1     0    0    0    3
2    F24B0013K     2    1     0    0    0    3
3    F24B0018K     2    2     0    0    0    4
4    F24B0020K     2    2     0    0    0    4
5    F24B0028K     2    0     0    0    0    2
6    F24B0032K     2    2     2    2    1    9
7    F24B0033K     2    2     2    2    2   10
8    F24B0040P     0    0     0    2    2    4
9    F24B0045P     2    2     2    0    2    8
10   F24B0050P     2    1     1    0    2    6
11   F24B0072K     2    2     0    0    0    4
12   F24B0236P     2    2     2    2    2   10
13   F24B0242P     2    2     0    2    2    8
14   F24B0248P     2    2     2    1    2    9
15   F24B0250P     0    2     0    2    2    6
16   F24B0253P     2    2     2    0    0    6
17   F24B0256P     2    2     2    2    2   10
18   F24B0257P     2    2     2    2    2   10
19   F24B0259P     2    2     2    2    2   10
20   F24B0264P     2    2     0    0    0    4
21   F24B0269P     2    0     0    0    0    2
22   F24B0271P     2    2     2    2    2   10
23   F24B0273P     2    2     2    2    2   10
24   F24B0274P     2    2     2    2    2   10
25   F24B0275P     2    2     2    2    2   10
26   F24B0277P     2    2     2    2    2   10
27   F24B0281P     2    2     2    2    2   10
28   F24B0284P     2    2     2    2    2   10
29   F24B0287P     2    2     2    2    2   10
30   F24B0288P     2    2     2    2    2   10
31   F24B0289P     2    2     2    0    0    6
32   F24B0292P     0    0     0    2    0    2
33   F24B0293P     2    2     2    2    0    8
34   F24B0296P     2    2     2    0    2    8
35   F24B0297P     2    2     2    2    0    8
36   F24B0306P     2    2     0    2    2    8
37   F24B0307P     2    2     2    2    2   10
38   F24B0309P     2    2     2    2    2   10
39   F24B0313P     0    2     0    2    2    6
40   F24B0320P     2    2     2    2    2   10
41   F24B0328P     0    2     2    2    2    8
42   F24B0335P     2    1     2    0    2    7
43   F24B0337P     0    2     0    0    0    2

In [44]:
table.to_csv("../data/udhb_povinne.csv")

In [46]:
table.sort_values(by="sum", ascending=False)

ntb        site  gis  http  nlp  pdf  sum
osCislo
F23B0247P     2    2     2    2    2   10
F23B0265P     2    2     2    2    2   10
F23B0215P     2    2     2    2    2   10
F23B0216P     2    2     2    2    2   10
F23B0218P     2    2     2    2    2   10
...         ...  ...   ...  ...  ...  ...
F23B0064K     0    1     0    0    0    1
F23B0024K     0    1     0    0    0    1
F23B0376P     0    1     0    0    0    1
F23B0316P     0    0     0    0    0    0
F23B0371P     0    0     0    0    0    0

[83 rows x 6 columns]

In [47]:
(table["sum"] >= 8).sum()

69